#!/usr/bin/env python
# encoding: utf-8
#
# Copyright (c) 2017 Dean Jackson <deanishe@deanishe.net>
#
# MIT Licence. See http://opensource.org/licenses/MIT
#
# Created on 2017-12-24
#

"""Benchmark the speed of cite.js."""


from __future__ import print_function, absolute_import

from contextlib import contextmanager
import os
import subprocess
import sys
from time import time

REPS = 20
TIMES = []

HERE = os.path.dirname(__file__)
STYLE = os.path.expanduser('~/Zotero/styles/apa.csl')
LOCALES = os.path.join(HERE, 'locales')
DATA = os.path.join(HERE, 'test.json')


def log(s, *args):
    """Simple STDERR logger."""
    if args:
        s = s % args
    print(s, file=sys.stderr)


@contextmanager
def timed(name):
    start = time()
    yield
    d = time() - start
    log('[%s] %0.2fs', name, d)
    TIMES.append(d)


for i in range(REPS):
    with timed('cite'):
        subprocess.check_output(['./cite', '-L', LOCALES, STYLE, DATA])


log('[average] %0.3fs', sum(TIMES) / len(TIMES))
